version: 1
formatters:
  timed:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    (): coloredlogs.ColoredFormatter
    format: '%(levelname)s %(name)s %(message)s'
loggers:
  proxmoxer:
    level: WARNING
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: timed
    filename: /var/log/plutex-promo-balance.log
root:
  level: DEBUG
  handlers: [console, file]
disable_existing_loggers: False
